---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "user-api-service"
  namespace: "default"
  labels:
    app: "user-api"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "user-api"
  type: "LoadBalancer"
  loadBalancerIP: ""
