---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "user-api"
  namespace: "default"
  labels:
    app: "user-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "user-api"
  template:
    metadata:
      labels:
        app: "user-api"
    spec:
      containers:
      - name: "user-api-sejuta-cita-sha256-1"
        image: "gcr.io/lively-goal-318409/user-api-sejuta-cita@sha256:9e2e748c903b9734cb74478aafcff0c8cb519742e3de256a7ee22621a4dafc2b"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "user-api-hpa-xkrc"
  namespace: "default"
  labels:
    app: "user-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "user-api"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80